/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSkillsRouteImport } from './routes/_authenticated/skills'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMissionsRouteImport } from './routes/_authenticated/missions'
import { Route as AuthenticatedMarketRouteImport } from './routes/_authenticated/market'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedIndustriesRouteImport } from './routes/_authenticated/industries'
import { Route as AuthenticatedFlightLogsRouteImport } from './routes/_authenticated/flight-logs'
import { Route as AuthenticatedFlightRouteImport } from './routes/_authenticated/flight'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrewRouteImport } from './routes/_authenticated/crew'
import { Route as AuthenticatedBasesRouteImport } from './routes/_authenticated/bases'
import { Route as AuthenticatedAircraftRouteImport } from './routes/_authenticated/aircraft'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSkillsRoute = AuthenticatedSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMissionsRoute = AuthenticatedMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketRoute = AuthenticatedMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndustriesRoute = AuthenticatedIndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFlightLogsRoute = AuthenticatedFlightLogsRouteImport.update({
  id: '/flight-logs',
  path: '/flight-logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFlightRoute = AuthenticatedFlightRouteImport.update({
  id: '/flight',
  path: '/flight',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrewRoute = AuthenticatedCrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBasesRoute = AuthenticatedBasesRouteImport.update({
  id: '/bases',
  path: '/bases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAircraftRoute = AuthenticatedAircraftRouteImport.update({
  id: '/aircraft',
  path: '/aircraft',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/aircraft': typeof AuthenticatedAircraftRoute
  '/bases': typeof AuthenticatedBasesRoute
  '/crew': typeof AuthenticatedCrewRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/flight': typeof AuthenticatedFlightRoute
  '/flight-logs': typeof AuthenticatedFlightLogsRoute
  '/industries': typeof AuthenticatedIndustriesRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/market': typeof AuthenticatedMarketRoute
  '/missions': typeof AuthenticatedMissionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/skills': typeof AuthenticatedSkillsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/aircraft': typeof AuthenticatedAircraftRoute
  '/bases': typeof AuthenticatedBasesRoute
  '/crew': typeof AuthenticatedCrewRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/flight': typeof AuthenticatedFlightRoute
  '/flight-logs': typeof AuthenticatedFlightLogsRoute
  '/industries': typeof AuthenticatedIndustriesRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/market': typeof AuthenticatedMarketRoute
  '/missions': typeof AuthenticatedMissionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/skills': typeof AuthenticatedSkillsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/aircraft': typeof AuthenticatedAircraftRoute
  '/_authenticated/bases': typeof AuthenticatedBasesRoute
  '/_authenticated/crew': typeof AuthenticatedCrewRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/flight': typeof AuthenticatedFlightRoute
  '/_authenticated/flight-logs': typeof AuthenticatedFlightLogsRoute
  '/_authenticated/industries': typeof AuthenticatedIndustriesRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/market': typeof AuthenticatedMarketRoute
  '/_authenticated/missions': typeof AuthenticatedMissionsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/skills': typeof AuthenticatedSkillsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/aircraft'
    | '/bases'
    | '/crew'
    | '/dashboard'
    | '/finance'
    | '/flight'
    | '/flight-logs'
    | '/industries'
    | '/maintenance'
    | '/market'
    | '/missions'
    | '/settings'
    | '/skills'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/aircraft'
    | '/bases'
    | '/crew'
    | '/dashboard'
    | '/finance'
    | '/flight'
    | '/flight-logs'
    | '/industries'
    | '/maintenance'
    | '/market'
    | '/missions'
    | '/settings'
    | '/skills'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/aircraft'
    | '/_authenticated/bases'
    | '/_authenticated/crew'
    | '/_authenticated/dashboard'
    | '/_authenticated/finance'
    | '/_authenticated/flight'
    | '/_authenticated/flight-logs'
    | '/_authenticated/industries'
    | '/_authenticated/maintenance'
    | '/_authenticated/market'
    | '/_authenticated/missions'
    | '/_authenticated/settings'
    | '/_authenticated/skills'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/skills': {
      id: '/_authenticated/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthenticatedSkillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missions': {
      id: '/_authenticated/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof AuthenticatedMissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market': {
      id: '/_authenticated/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AuthenticatedMarketRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/industries': {
      id: '/_authenticated/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof AuthenticatedIndustriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flight-logs': {
      id: '/_authenticated/flight-logs'
      path: '/flight-logs'
      fullPath: '/flight-logs'
      preLoaderRoute: typeof AuthenticatedFlightLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flight': {
      id: '/_authenticated/flight'
      path: '/flight'
      fullPath: '/flight'
      preLoaderRoute: typeof AuthenticatedFlightRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crew': {
      id: '/_authenticated/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof AuthenticatedCrewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bases': {
      id: '/_authenticated/bases'
      path: '/bases'
      fullPath: '/bases'
      preLoaderRoute: typeof AuthenticatedBasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aircraft': {
      id: '/_authenticated/aircraft'
      path: '/aircraft'
      fullPath: '/aircraft'
      preLoaderRoute: typeof AuthenticatedAircraftRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAircraftRoute: typeof AuthenticatedAircraftRoute
  AuthenticatedBasesRoute: typeof AuthenticatedBasesRoute
  AuthenticatedCrewRoute: typeof AuthenticatedCrewRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedFlightRoute: typeof AuthenticatedFlightRoute
  AuthenticatedFlightLogsRoute: typeof AuthenticatedFlightLogsRoute
  AuthenticatedIndustriesRoute: typeof AuthenticatedIndustriesRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedMarketRoute: typeof AuthenticatedMarketRoute
  AuthenticatedMissionsRoute: typeof AuthenticatedMissionsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSkillsRoute: typeof AuthenticatedSkillsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAircraftRoute: AuthenticatedAircraftRoute,
  AuthenticatedBasesRoute: AuthenticatedBasesRoute,
  AuthenticatedCrewRoute: AuthenticatedCrewRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedFlightRoute: AuthenticatedFlightRoute,
  AuthenticatedFlightLogsRoute: AuthenticatedFlightLogsRoute,
  AuthenticatedIndustriesRoute: AuthenticatedIndustriesRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedMarketRoute: AuthenticatedMarketRoute,
  AuthenticatedMissionsRoute: AuthenticatedMissionsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSkillsRoute: AuthenticatedSkillsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
